pipeline:
  prep:
    image: library/debian:unstable
    commands:
      - apt-get update
      - apt-get -y install devscripts git-buildpackage libusb-1.0-0-dev pkg-config libreadline-dev
      - make
